name: molecule lint

on:
    push:
        branches:
            - main
            - feature/*
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - lint
        uses: MonolithProjects/action-molecule@v1.4.4
        with:
          molecule_command: lint
