name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_DOCS_VERSION: "v0.16.0"
  TFLINT_VERSION: "v0.36.2"

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
